// store/language.js
import { ref, computed } from 'vue'
import { auth, db, doc, getDoc, setDoc, serverTimestamp } from '../firebase'

// Available languages
export const languages = {
  en: {
    code: 'en',
    name: 'English',
    flag: '🇺🇸',
    dir: 'ltr'
  },
  tl: {
    code: 'tl',
    name: 'Filipino',
    flag: '🇵🇭',
    dir: 'ltr'
  }
  // Add more languages as needed
}

// Language translations
export const translations = {
  en: {
    // In your store/language.js, add these to the 'en' section:
    // In your store/language.js, add to the 'en' section:
    dashboard: 'Dashboard',
    uploadImage: 'Upload Image',
    history: 'History',
    diseaseInfo: 'Disease Info',
    profile: 'Profile',
    myProfile: 'My Profile',
    settings: 'Settings',
    logout: 'Logout',
    user: 'User',

    // Dashboard Page
    dashboardTitle: 'Dashboard Overview',
    dashboardSubtitle: 'Real-time insights and performance metrics',
    totalAnalyzed: 'Total Leaves Analyzed',
    healthyPlants: 'Healthy Plants',
    infectedPlants: 'Infected Plants',
    modelAccuracy: 'Model Accuracy',
    systemStatus: 'System Status',
    liveMonitoring: 'Live monitoring & performance metrics',
    online: 'Online',
    offline: 'Offline',
    mlModel: 'ML Model',
    operational: 'Operational',
    lastUpdate: 'Last Update',
    queue: 'Queue',
    pending: '{count} pending',
    avgProcessing: 'Avg. Processing',
    locale: 'en-US', // For date formatting

    // Common
    appName: 'Cu-Scan Plant Disease Detection',
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    confirm: 'Confirm',
    back: 'Back',
    next: 'Next',
    done: 'Done',

    // Navigation
    navHome: 'Home',
    navUpload: 'Upload',
    navHistory: 'History',
    navAbout: 'About',
    navProfile: 'Profile',
    navLogout: 'Logout',
    navLogin: 'Login',
    navRegister: 'Register',
    features: 'Features',
    howItWorks: 'How It Works',
    research: 'Research',
    getStarted: 'Get Started',

    // Hero Section
    heroBadge: 'AI-Powered Agriculture',
    heroTitle1: 'Smart Detection for',
    heroTitle2: 'Healthy Cucumbers',
    heroDescription: 'Advanced deep learning system for early detection and diagnosis of cucumber plant diseases. Upload images, get instant AI analysis, and protect your crops with 95% accuracy.',
    startDetection: 'Start Detection',
    watchDemo: 'Watch Demo',
    imagesAnalyzed: 'Images Analyzed',
    detectionAccuracy: 'Detection Accuracy',
    diseasesIdentified: 'Diseases Identified',

    // Features Section
    whyChoose: 'Why Choose Cucumber',
    ai: 'AI',
    cuttingEdge: 'Cutting-edge technology for modern agriculture',

    // Feature Cards
    feature1Title: 'Advanced AI Models',
    feature1Desc: 'State-of-the-art deep learning algorithms with 95%+ accuracy',
    feature2Title: 'Real-time Analysis',
    feature2Desc: 'Get instant results and actionable insights within seconds',
    feature3Title: 'Multi-Disease Detection',
    feature3Desc: 'Identify 10+ common cucumber diseases with precision',
    feature4Title: 'Prevention Tips',
    feature4Desc: 'Get expert recommendations for disease prevention',

    // CTA Section
    ctaTitle: 'Ready to Protect Your Crops?',
    ctaDescription: 'Join hundreds of farmers and agricultural experts using Cu-Scan for disease prevention.',
    ctaButton: 'Start Free Analysis',

    // Footer
    product: 'Product',
    pricing: 'Pricing',
    api: 'API',
    resources: 'Resources',
    documentation: 'Documentation',
    blog: 'Blog',
    company: 'Company',
    contact: 'Contact',
    careers: 'Careers',
    stayUpdated: 'Stay updated',
    subscribeText: 'Subscribe for product updates and research news.',
    emailPlaceholder: 'Your email',
    subscribe: 'Subscribe',
    allRightsReserved: 'All rights reserved.',
    privacy: 'Privacy',
    terms: 'Terms',

    // Modal Titles
    modalFeatures: 'Features',
    modalHowItWorks: 'How It Works',
    modalResearch: 'Research & Development',
    modalDemo: 'Watch Demo',
    modalPricing: 'Pricing Plans',
    modalAPI: 'API Documentation',
    modalDocumentation: 'Documentation',
    modalBlog: 'Blog & Updates',
    modalAbout: 'About Us',
    modalContact: 'Contact Us',
    modalCareers: 'Careers',

    // Modal Content
    modalFeaturesSubtitle: 'Everything you need for effective cucumber disease management',
    modalHowItWorksSubtitle: 'Simple steps to protect your crops',
    modalResearchSubtitle: 'Backed by scientific research and continuous innovation',
    modalDemoSubtitle: 'See how Cu-Scan works in action',

    // Modal Features
    modalFeature1Title: 'AI-Powered Detection',
    modalFeature1Desc: '95%+ accuracy with deep learning models',
    modalFeature2Title: 'Real-time Analysis',
    modalFeature2Desc: 'Results in under 2 seconds',
    modalFeature3Title: 'Multi-Disease Detection',
    modalFeature3Desc: 'Identify 10+ cucumber diseases',
    modalFeature4Title: 'Detailed Reports',
    modalFeature4Desc: 'PDF reports with treatment plans',
    modalFeature5Title: 'Mobile App',
    modalFeature5Desc: 'iOS & Android support',
    modalFeature6Title: 'Batch Processing',
    modalFeature6Desc: 'Upload multiple images at once',

    // How It Works Steps
    step1Title: 'Upload Image',
    step1Desc: 'Take or upload a clear photo of cucumber leaves',
    step2Title: 'AI Analysis',
    step2Desc: 'Our deep learning model analyzes the image in seconds',
    step3Title: 'Get Diagnosis',
    step3Desc: 'Receive detailed disease identification and severity',
    step4Title: 'Treatment Plan',
    step4Desc: 'Get expert recommendations for treatment and prevention',

    // Research Modal
    researchAccuracy: 'Detection Accuracy',
    researchImages: 'Training Images',
    researchDiseases: 'Diseases Detected',
    researchPoint1: 'Published in Agricultural AI Journals',
    researchPoint2: 'Collaboration with Agricultural Universities',
    researchPoint3: 'Continuous Model Improvements',

    // Demo Modal
    demoVideoPlaceholder: 'Demo video will play here',
    demoOverview: 'Demo Overview',
    demoStep1: 'Upload cucumber leaf image',
    demoStep2: 'AI analysis in real-time',
    demoStep3: 'Get detailed diagnosis report',
    demoStep4: 'View treatment recommendations',

    // Default Modal
    comingSoon: 'Content for {modal} is coming soon!',

    // Modal Footer
    getStarted: 'Get Started',
    close: 'Close',

    // Footer Tagline
    brandSubtitle: 'Plant health intelligence',
    workspace: 'Workspace',
    newScan: 'New scan',
    scanHistory: 'Scan history',
    diseaseGuide: 'Disease guide',
    community: 'Community',
    needHelp: 'Need help?',
    visitForum: 'Visit the community forum',
    accountSettings: 'Account settings',
    preferences: 'Preferences',
    signOut: 'Sign out',
    expandSidebar: 'Expand sidebar',
    collapseSidebar: 'Collapse sidebar',
    displaySettings: 'Display Settings',
    settingsSubtitle: 'Quick theme, language, font size, and layout controls.',
    theme: 'Theme',
    language: 'Language',
    lightMode: 'Light mode',
    darkMode: 'Dark mode',
    fontSize: 'Font size',
    normal: 'Normal',
    largeAccessibility: 'Large (accessibility)',
    layoutMode: 'Layout mode',
    fullLayout: 'Full layout',
    compactLayout: 'Compact layout',
    homeHeroLine1: 'Protect every leaf',
    homeHeroLine2: 'before disease spreads.',
    homeTrustNoCard: 'No credit card required',
    homeTrustFastResults: 'Results in seconds',
    livePlantScan: 'LIVE PLANT SCAN',
    moreOptions: 'More options',
    analysisComplete: 'ANALYSIS COMPLETE',
    healthyPlantDetected: 'Healthy plant detected',
    fastResults: 'Fast results',
    trustedGrowers: 'Trusted plant intelligence for modern growers.',
    builtForDecisions: 'Built for better decisions',
    homeFeaturesTitle: 'Everything you need to act',
    homeFeaturesTitleAccent: 'early and confidently.',
    learnMore: 'Learn more',
    simpleByDesign: 'Simple by design',
    homeStepsTitle: 'From photo to',
    homeStepsTitleAccent: 'peace of mind.',
    homeStepsDescription: 'Cu-Scan turns a clear leaf photo into an actionable diagnosis in four straightforward steps.',
    seeHowItWorks: 'See how it works',
    startToday: 'Start today',
    seconds: 'seconds',
    loginWelcome: 'Welcome back',
    loginHeroTitle: 'Grow with confidence,',
    loginHeroAccent: 'one scan at a time.',
    loginHeroDescription: 'Return to your plant health workspace, view your history, and make informed decisions for every crop.',
    detectionAccuracyLabel: 'Detection accuracy',
    averageAnalysis: 'Average analysis',
    systemReady: 'System ready',
    aiModelOnline: 'AI model online',
    dashboardReady: 'Your crop intelligence dashboard is ready when you are.',
    signInToCuScan: 'Sign in to Cu-Scan',
    goodToSeeYou: 'Good to see you again.',
    continueWorkspace: 'Enter your details to continue to your workspace.',
    emailAddress: 'Email address',
    password: 'Password',
    enterPassword: 'Enter your password',
    hidePassword: 'Hide password',
    showPassword: 'Show password',
    rememberMe: 'Remember me',
    forgotPassword: 'Forgot password?',
    signIn: 'Sign in',
    signingIn: 'Signing in',
    newToCuScan: 'New to Cu-Scan?',
    createFreeAccount: 'Create your free account',
    verifyYourEmail: 'Verify your email',
    verificationSent: 'We sent a verification link to',
    verifyThenReturn: 'Verify your account, then return here to sign in.',
    resendVerificationEmail: 'Resend verification email',
    emailRequired: 'Email is required',
    validEmailRequired: 'Please enter a valid email address',
    passwordRequired: 'Password is required',
    passwordMinimum: 'Password must be at least 6 characters',
    registerEyebrow: 'Smarter crop care starts here',
    registerHeroTitle: 'See what your plants are trying to tell you.',
    registerHeroDescription: 'Create your workspace to identify plant diseases, track every scan, and make confident crop decisions.',
    fastAiScans: 'Fast, AI-powered scans',
    fastAiScansDescription: 'Get clear insights from a single photo.',
    organizedScanHistory: 'Organized scan history',
    scanHistoryDescription: 'Keep your crop health records in one place.',
    builtForGrowers: 'Built for growers',
    growerGuidance: 'Useful guidance when it matters most.',
    createAccount: 'Create your account',
    protectCrops: 'Start protecting your crops.',
    setupTime: 'It takes less than a minute to get set up.',
    fullName: 'Full name',
    yourFullName: 'Your full name',
    createPassword: 'Create a password',
    passwordStrength: 'Password strength',
    useStrongPassword: 'Use 8+ characters with uppercase, lowercase, a number, and a symbol.',
    confirmPassword: 'Confirm password',
    repeatPassword: 'Repeat your password',
    agreeToTerms: 'I agree to the',
    and: 'and',
    createAccountButton: 'Create account',
    creatingAccount: 'Creating account',
    alreadyHaveAccount: 'Already have an account?',
    checkYourEmail: 'Check your email',
    activateAccount: 'Verify your email to activate your account.',
    goToSignIn: 'Go to sign in',
    resendEmail: 'Resend email',
    weak: 'Weak',
    good: 'Good',
    strong: 'Strong',
    none: 'None',
    nameRequired: 'Name is required',
    confirmPasswordRequired: 'Please confirm your password',
    passwordsDoNotMatch: 'Passwords do not match',
    acceptTermsRequired: 'You must accept the terms and conditions',
    forgotHeroTitle: 'Reset Your Password',
    forgotHeroDescription: 'Enter your email to receive reset instructions',
    checkYourEmailBang: 'Check your email!',
    resetInstructionsSent: "We've sent password reset instructions to",
    sendResetLink: 'Send Reset Link',
    sending: 'Sending...',
    backToLogin: 'Back to Login',
    profileSettings: 'Profile Settings',
    manageAccount: 'Manage your account information',
    loadingProfile: 'Loading profile data...',
    retry: 'Retry',
    emailVerified: 'Email Verified',
    emailNotVerified: 'Email Not Verified',
    memberSince: 'Member since',
    totalAnalyses: 'Total Analyses',
    healthy: 'Healthy',
    infected: 'Infected',
    recentSevenDays: 'Recent (7 days)',
    recentAnalyses: 'Recent Analyses',
    noAnalysesStart: 'No analyses found. Start by uploading an image.',
    noImage: 'No Image',
    confidence: 'Confidence',
    accountDetails: 'Account Details',
    userId: 'User ID',
    accountCreated: 'Account Created',
    lastLogin: 'Last Login',
    emailStatus: 'Email Status',
    verified: 'Verified',
    pendingVerification: 'Pending Verification',
    accountActions: 'Account Actions',
    uploadNewImage: 'Upload New Image',
    viewHistory: 'View History',
    resetPassword: 'Reset Password',
    logout: 'Logout',
    notAvailable: 'N/A',
    unknown: 'Unknown',
    noUserLoggedIn: 'No user logged in',
    failedLoadProfile: 'Failed to load user data. Please try again.',
    diseaseInfoLabel: 'Disease Info',
    diseaseReference: 'Disease Reference',
    cucumberDisease: 'Cucumber Disease',
    knowledgeBase: 'Knowledge Base',
    diseaseGuideSubtitle: 'Comprehensive guide to identifying, preventing, and treating cucumber diseases.',
    searchDiseases: 'Search diseases...',
    categoryAll: 'All',
    categoryFungal: 'Fungal',
    categoryBacterial: 'Bacterial',
    categoryViral: 'Viral',
    categorySoil: 'Soil',
    totalDiseases: 'Total Diseases',
    highRisk: 'High Risk',
    fungal: 'Fungal',
    bacterial: 'Bacterial',
    showingDiseases: 'Showing {shown} of {total} diseases',
    clearFilters: 'Clear filters',
    keySymptoms: 'Key Symptoms',
    aiDetection: 'AI Detection',
    viewDetails: 'View Details',
    noDiseasesFound: 'No diseases found',
    adjustSearchFilters: 'Try adjusting your search or filters',
    resetFilters: 'Reset Filters',
    needDiagnosis: 'Need a diagnosis?',
    uploadAffectedPlants: 'Upload images of affected plants for AI-powered analysis',
    severityHigh: 'High',
    severityMedium: 'Medium',
    soilBorne: 'Soil-borne',
    historyTitle: 'Analysis History',
    historySubtitle: 'Track all your cucumber leaf analyses and results',
    refresh: 'Refresh',
    downloadAllPdf: 'Download All as PDF',
    healthyPlants: 'Healthy Plants',
    infectedDetected: 'Infected Detected',
    loadingHistory: 'Loading your analysis history...',
    searchHistory: 'Search by disease name, date, or status...',
    status: 'Status',
    dateRange: 'Date Range',
    sortBy: 'Sort by',
    newestFirst: 'Newest First',
    oldestFirst: 'Oldest First',
    highConfidence: 'High Confidence',
    lowConfidence: 'Low Confidence',
    nameAZ: 'Name A-Z',
    nameZA: 'Name Z-A',
    showingAnalyses: 'Showing {shown} of {total} analyses',
    filtered: 'filtered',
    detectedDisease: 'Detected Disease',
    actions: 'Actions',
    image: 'Image',
    filename: 'Filename',
    date: 'Date',
    noMatchingAnalyses: 'No matching analyses found',
    noHistoryYet: 'No analysis history yet',
    adjustHistorySearch: 'Try adjusting your filters or search terms',
    uploadFirstImage: 'Upload your first cucumber leaf image to get started',
    uploadFirst: 'Upload First Image',
    clearAllFilters: 'Clear All Filters',
    grid: 'Grid',
    table: 'Table',
    analysisDetails: 'Analysis Details',
    fileInformation: 'File Information',
    fileSize: 'File Size',
    uploadDate: 'Upload Date',
    analysisId: 'Analysis ID',
    analysisResults: 'Analysis Results',
    symptomsIdentified: 'Symptoms Identified',
    recommendations: 'Recommendations',
    pdfReport: 'PDF Report',
    downloadPdfReport: 'Download PDF Report',
    reportOptionsSingle: 'Customize Analysis Report',
    reportOptionsBatch: 'Customize Batch Report',
    chooseReportContent: 'Choose which sections to include in the PDF.',
    reportSections: 'Report sections',
    reportIncludeImage: 'Plant image',
    reportIncludeFileInfo: 'File information',
    reportIncludeResults: 'Analysis results',
    reportIncludeSymptoms: 'Identified symptoms',
    reportIncludeRecommendations: 'Recommendations',
    reportIncludeSummary: 'Summary statistics',
    reportColumns: 'Result columns',
    reportIncludeFilename: 'Filename',
    reportIncludeStatus: 'Status',
    reportIncludeDisease: 'Disease',
    reportIncludeConfidence: 'Confidence',
    reportIncludeDate: 'Date',
    generatePdf: 'Generate PDF',
    noReportSectionsSelected: 'Select at least one section or column.',
    reportGenerated: 'Your PDF report is ready.',
    reportTitle: 'Cucumber Disease Analysis Report',
    batchReportTitle: 'Batch Analysis Report',
    reportDateGenerated: 'Report Generated',
    reportSummary: 'Summary Statistics',
    totalImages: 'Total Images',

    pestSavedToFirestore: 'Pest scan photo and result saved to Firestore.',
    pestSaveFailed: 'Could not save the pest scan to Firestore. Check your connection and permissions.',
    pestSignInToSave: 'Sign in to save pest scan photos to your Firestore account.',
    pestImageTooLarge: 'Could not compress this photo enough to store it in Firestore.',
    reanalyze: 'Reanalyze',
    clearConversation: 'Clear conversation',
    uploadTitle: 'Upload Cucumber Image',
    uploadSubtitle: 'Upload or capture an image for disease detection analysis',
    scanScopeWarningTitle: 'Scan scope',
    scanScopeWarning: 'Only scan cucumber fruit or leaves. Other image types are not blocked yet, so results may be inaccurate. Support for additional images is planned for a future release.',
    model: 'Model',
    loaded: 'Loaded',
    notLoaded: 'Not Loaded',
    classes: 'Classes',
    diseasesCount: '{count} diseases',
    backend: 'Backend',
    running: 'Running',
    backendRequired: 'Backend Connection Required',
    backendCannotConnect: 'Cannot connect to backend server',
    startBackend: 'To start the backend:',
    openTerminal: 'Open a terminal/command prompt',
    navigateBackend: 'Navigate to: C:\\cudics\\backend',
    runBackend: 'Run: python app.py',
    offlineLocalNote: 'You can still process images locally without backend using mock data.',
    uploadFile: 'Upload File',
    useCamera: 'Use Camera',
    dropImage: 'Drop image here',
    orBrowse: 'or click to browse',
    supportsImageFiles: 'Supports: JPG, PNG, JPEG (Max 10MB)',
    retake: 'Retake',
    usePhoto: 'Use Photo',
    cameraInstructions: 'Position the cucumber leaf in the center frame for best results',
    scanDisease: 'Scan Disease',
    processing: 'Processing...',
    scanForPest: 'Scan for Pest',
    scanning: 'Scanning...',
    selectImageHint: 'Select an image to begin processing',
    backendDisconnectedHint: 'Backend not connected. Using mock data for disease detection only.',
    uploadToSeeResults: 'Upload an image to see analysis results',
    analyzingImage: 'Analyzing image for diseases...',
    secondsWait: 'This may take a few seconds',
    processingErrorTitle: 'Processing Error',
    trySampleData: 'Try with sample data instead',
    pestScanResult: 'Pest Scan Result',
    pestGuidance: 'Detected pest and treatment guidance',
    detectedPest: 'Detected Pest',
    pest: 'Pest',
    pestScansCount: 'Pest Scans',
    pestOrDisease: 'Pest / Disease',
    recommendedCure: 'Recommended Treatment',
    diseaseProbabilities: 'Disease Probabilities',
    detectedDisease: 'Detected Disease',
    recommendationsFor: 'Recommendations for {disease}',
    processed: 'Processed',
    sampleDataNote: 'Note: Results based on sample data. Start backend for real analysis.',
    saveReport: 'Save Report',
    recentUploads: 'Recent Analyses',
    fileSizeExceeded: 'File size exceeds 10MB. Please choose a smaller image.',
    cameraAccessError: 'Unable to access camera. Please check permissions.',
    cameraInsecureContext: 'Camera access requires a secure page. Open this site over HTTPS (localhost is allowed for local testing).',
    cameraPermissionDenied: 'Camera access was denied. Allow camera access in your browser settings, then reload this page.',
    cameraNotFound: 'No camera was found on this device.',
    cameraUnavailable: 'The camera is unavailable or already in use by another app.',
    cannotConnectBackend: 'Cannot connect to backend server. Please make sure:',
    saveHistoryLogin: 'Want to save your analysis history? Please log in.',
    reportSaved: 'Report saved successfully!',
    discussionBoard: 'Discussion Board',
    growerCommunityTitle: 'Grower Community & Knowledge Center',
    forumDescription: 'Share insights, ask questions, and collaborate with fellow growers in a focused, practical forum.',
    recentPosts: 'Recent posts',
    weeklyEngagement: 'Weekly engagement',
    newDiscussion: 'New discussion',
    createPost: 'Create a post',
    concisePost: 'Keep your post concise and actionable.',
    discussionTitle: 'Discussion title',
    shareWithCommunity: 'Share a problem, solution, or observation with the community.',
    addPhoto: 'Add photo',
    replacePhoto: 'Replace photo',
    removePhoto: 'Remove photo',
    selectedPhoto: 'Selected photo preview',
    invalidPhoto: 'Choose a valid image file.',
    photoTooLarge: 'Photo must be 10 MB or smaller.',
    photoCompressionFailed: 'Could not prepare this photo for Firestore. Try another image.',
    posting: 'Posting...',
    postDiscussion: 'Post Discussion',
    loadingDiscussions: 'Loading discussions...',
    noDiscussions: 'No discussions yet. Start the conversation with a helpful post.',
    communityMember: 'Community Member',
    postedGrowerForum: 'Posted in Grower Forum',
    reply: 'Reply',
    cancel: 'Cancel',
    share: 'Share',
    hideReplies: 'Hide replies',
    showReplies: 'Show replies ({count})',
    writeReply: 'Write your reply...',
    postingReply: 'Posting reply...',
    submitReply: 'Submit reply',
    communityGuidelines: 'Community guidelines',
    respectfulPosts: 'Keep posts respectful and on-topic.',
    clearContext: 'Share clear images or context.',
    actionableAdvice: 'Offer constructive, actionable advice.',
    popularTopics: 'Popular topics',
    plantHealth: 'Plant health',
    pestControl: 'Pest control',
    harvestTips: 'Harvest tips',
    justNow: 'Just now',
    writeOrAddPhoto: 'Please write something or add a photo.',
    signInToPost: 'Please sign in before posting to the forum.',
    postPublished: 'Post published successfully.',
    postFailed: 'Unable to post right now. Please try again.',
    enterReply: 'Please enter a reply before submitting.',
    signInToReply: 'Please sign in before replying.',
    replyPublished: 'Reply posted successfully.',
    replyFailed: 'Unable to submit reply. Please try again.',
    untitledDiscussion: 'Untitled discussion',
    welcomeBack: 'Welcome back',
    farmer: 'Farmer',
    notifications: 'Notifications',
    markAllRead: 'Mark all as read',
    noNewNotifications: 'No new notifications',
    viewAll: 'View all',
    notificationUnread: '{count} unread notifications',
    notificationUpdates: '{count} unread updates',
    allCaughtUp: "You're all caught up",
    restartService: 'Restart Service',
    runDiagnostic: 'Run Diagnostic',
    viewLogs: 'View Logs',
    modelStatusCheck: 'The machine learning model is operational.',
    confirmRestart: 'Are you sure you want to restart the service?',
    serviceRestarted: 'Service restarted successfully.',
    diagnosticRunning: 'System diagnostic is running.',
    exportStarted: 'Analytics export started.',
    analyticsTitle: 'Process Analytics',
    analyticsSubtitle: 'Performance insights and process monitoring',
    timeRange: 'Time Range',
    totalProcesses: 'Total Processes',
    fromLastPeriod: 'from last period',
    completed: 'Completed',
    successRate: 'success rate',
    avgProcessingTime: 'Avg Processing Time',
    processesUnder5s: '{count} processes under 5s',
    activeProcesses: 'Active Processes',
    currentlyInProgress: 'Currently in progress',
    processVolume: 'Process Volume',
    currentPeriod: 'Current Period',
    statusDistribution: 'Status Distribution',
    statuses: 'Statuses',
    performanceMetrics: 'Performance Metrics',
    processingTime: 'Processing Time',
    recentActivity: 'Recent Activity',
    noPreviousData: 'No previous data',
    peakVolume: 'Peak Volume',
    processCountValue: '{count} processes',
    highestDailyCount: 'Highest single-day process count',
    averageSuccessRate: 'Avg. Success Rate',
    processCompletionPercentage: 'Process completion percentage',
    responseTime: 'Response Time',
    averageProcessingDuration: 'Average processing duration',
    activeSessions: 'Active Sessions',
    currentlyRunningProcesses: 'Currently running processes',
    imageAnalysisProcess: 'Image Analysis Process',
    processingDuration: '{duration} processing',
    recentActivityEmpty: 'No recent activity',
    startProcessAnalytics: 'Start a new process to see analytics',
    noActivityYet: 'No activity yet',
    allActivity: 'All Activity',
    openAssistant: 'Open Cu-Scan assistant',
    closeAssistant: 'Close Cu-Scan assistant',
    assistantAriaLabel: 'Cu-Scan plant assistant',
    assistant: 'Cu-Scan Assistant',
    plantSupport: 'Plant health support',
    howCanIHelp: 'How can I help with your plants?',
    askSymptoms: 'Ask about symptoms, disease prevention, or treatment options.',
    analyzingQuestion: 'Analyzing your question...',
    dismiss: 'Dismiss',
    askPlantProblem: 'Ask about a plant problem...',
    sendMessage: 'Send message',
    chatKeyboardHint: 'Enter to send · Shift + Enter for a new line',
    chatQuestion1: 'How do I treat powdery mildew?',
    chatQuestion2: 'Why are my leaves yellow with brown spots?',
    chatQuestion3: 'What causes sudden wilting?',
    chatQuestion4: 'How can I prevent fungal diseases?',
    chatQuestion5: 'What is an organic treatment for aphids?',
    chatQuestion6: 'How often should I water to avoid root rot?',
    assistantUnavailable: 'The assistant is temporarily unavailable. Showing general guidance instead.',
    confirmClearChat: 'Clear this conversation?',
    pendingStatus: 'Pending',
    failedStatus: 'Failed',
    errorStatus: 'Error',
    minutesAgo: '{count}m ago',
    hoursAgo: '{count}h ago',
    daysAgo: '{count}d ago',
    primaryNavigation: 'Primary navigation',
    dashboardHome: 'Cu-Scan dashboard',
    accessDenied: 'Access Denied',
    loginRequired: 'You need to be logged in to view this page.',
    goToLogin: 'Go to Login',
    unknownSize: 'Unknown size',
    invalidDate: 'Invalid date',
    invalidTime: 'Invalid time',
    pdfFailed: 'Failed to generate PDF report. Please try again.',
    batchPdfFailed: 'Failed to generate batch PDF report.',
    deleteAnalysisConfirm: 'Are you sure you want to delete this analysis? This action cannot be undone.',
    analysisDeleted: 'Analysis deleted successfully!',
    deleteFailed: 'Failed to delete analysis. Please try again.',
    passwordResetSent: 'Password reset email sent to {email}',
    verificationEmailSent: 'Verification email sent. Please check your inbox.',
    operationFailed: 'The request could not be completed. Please try again.',
    recently: 'Recently',
    bytes: 'Bytes',
    today: 'Today',
    thisWeek: 'This Week',
    thisMonth: 'This Month',
    allTime: 'All Time',
    tagline: 'Intelligent agriculture solutions for healthier crops',
  },

  tl: {
    dashboard: 'Dashboard',
    uploadImage: 'Mag-upload ng larawan',
    history: 'Kasaysayan',
    diseaseInfo: 'Impormasyon ng sakit',
    profile: 'Profile',
    myProfile: 'Aking profile',
    settings: 'Mga setting',
    logout: 'Mag-logout',
    user: 'User',
    dashboardTitle: 'Pangkalahatang-ideya ng dashboard',
    dashboardSubtitle: 'Mga real-time na insight at sukatan ng performance',
    totalAnalyzed: 'Kabuuang dahong nasuri',
    infectedPlants: 'Mga halamang may sakit',
    modelAccuracy: 'Katumpakan ng modelo',
    systemStatus: 'Katayuan ng system',
    liveMonitoring: 'Live na pagsubaybay at mga sukatan ng performance',
    online: 'Online',
    offline: 'Offline',
    mlModel: 'ML model',
    operational: 'Gumagana',
    lastUpdate: 'Huling update',
    queue: 'Pila',
    pending: '{count} nakapila',
    avgProcessing: 'Karaniwang pagproseso',
    locale: 'fil-PH',
    // Common
    appName: 'Pag-detect ng Sakit sa Pipino',
    loading: 'Naglo-load...',
    error: 'Error',
    success: 'Matagumpay',
    save: 'I-save',
    cancel: 'Kanselahin',
    delete: 'Burahin',
    confirm: 'Kumpirmahin',
    back: 'Bumalik',
    next: 'Susunod',
    done: 'Tapos',

    // Navigation
    navHome: 'Bahay',
    navUpload: 'Mag-upload',
    navHistory: 'Kasaysayan',
    navAbout: 'Tungkol',
    navProfile: 'Profile',
    navLogout: 'Mag-logout',
    navLogin: 'Mag-login',
    navRegister: 'Magrehistro',
    features: 'Mga Tampok',
    howItWorks: 'Paano Ito Gumagana',
    research: 'Pananaliksik',
    getStarted: 'Magsimula',

    // Hero Section
    heroBadge: 'Agrikultura na Pinapagana ng AI',
    heroTitle1: 'Matalinong Pag-detect para sa',
    heroTitle2: 'Malulusog na mga Pipino',
    heroDescription: 'Advanced deep learning system para sa maagang pag-detect at diagnosis ng mga sakit sa halamang pipino. Mag-upload ng mga larawan, kumuha ng agarang AI analysis, at protektahan ang iyong mga pananim na may 95% accuracy.',
    startDetection: 'Simulan ang Detection',
    watchDemo: 'Panoorin ang Demo',
    imagesAnalyzed: 'Mga Larawang Nasuri',
    detectionAccuracy: 'Accuracy ng Detection',
    diseasesIdentified: 'Mga Sakit na Natukoy',

    // Features Section
    whyChoose: 'Bakit Piliin ang Cucumber',
    ai: 'AI',
    cuttingEdge: 'Makabagong teknolohiya para sa modernong agrikultura',

    // Feature Cards
    feature1Title: 'Advanced AI Models',
    feature1Desc: 'Mga state-of-the-art deep learning algorithms na may 95%+ accuracy',
    feature2Title: 'Real-time Analysis',
    feature2Desc: 'Kumuha ng agarang resulta at actionable insights sa loob ng ilang segundo',
    feature3Title: 'Multi-Disease Detection',
    feature3Desc: 'Tukuyin ang 10+ karaniwang sakit ng pipino nang may precision',
    feature4Title: 'Mga Prevention Tips',
    feature4Desc: 'Kumuha ng expert recommendations para sa pag-iwas sa sakit',

    // CTA Section
    ctaTitle: 'Handa nang Protektahan ang Iyong mga Pananim?',
    ctaDescription: 'Sumali sa daan-daang magsasaka at agricultural experts na gumagamit ng Cu-Scan para sa pag-iwas sa sakit.',
    ctaButton: 'Simulan ang Libreng Analysis',

    // Footer
    product: 'Produkto',
    pricing: 'Presyo',
    api: 'API',
    resources: 'Mga Resources',
    documentation: 'Dokumentasyon',
    blog: 'Blog',
    company: 'Kumpanya',
    contact: 'Kontak',
    careers: 'Karerahan',
    stayUpdated: 'Manatiling updated',
    subscribeText: 'Mag-subscribe para sa product updates at research news.',
    emailPlaceholder: 'Iyong email',
    subscribe: 'Mag-subscribe',
    allRightsReserved: 'Lahat ng karapatan ay nakalaan.',
    privacy: 'Privacy',
    terms: 'Terms',

    // Modal Titles
    modalFeatures: 'Mga Tampok',
    modalHowItWorks: 'Paano Ito Gumagana',
    modalResearch: 'Pananaliksik at Pagpapaunlad',
    modalDemo: 'Panoorin ang Demo',
    modalPricing: 'Mga Presyo',
    modalAPI: 'API Documentation',
    modalDocumentation: 'Dokumentasyon',
    modalBlog: 'Blog at Updates',
    modalAbout: 'Tungkol sa Amin',
    modalContact: 'Kontakin Kami',
    modalCareers: 'Karerahan',

    // Modal Content
    modalFeaturesSubtitle: 'Lahat ng kailangan mo para sa epektibong pamamahala ng sakit sa pipino',
    modalHowItWorksSubtitle: 'Simpleng hakbang para protektahan ang iyong mga pananim',
    modalResearchSubtitle: 'Sinusuportahan ng siyentipikong pananaliksik at patuloy na pagbabago',
    modalDemoSubtitle: 'Tingnan kung paano gumagana ang Cu-Scan',

    // Modal Features
    modalFeature1Title: 'AI-Powered Detection',
    modalFeature1Desc: '95%+ accuracy gamit ang deep learning models',
    modalFeature2Title: 'Real-time Analysis',
    modalFeature2Desc: 'Resulta sa loob ng 2 segundo',
    modalFeature3Title: 'Multi-Disease Detection',
    modalFeature3Desc: 'Tukuyin ang 10+ sakit ng pipino',
    modalFeature4Title: 'Detailed Reports',
    modalFeature4Desc: 'PDF reports na may treatment plans',
    modalFeature5Title: 'Mobile App',
    modalFeature5Desc: 'Suporta sa iOS at Android',
    modalFeature6Title: 'Batch Processing',
    modalFeature6Desc: 'Mag-upload ng maraming larawan nang sabay-sabay',

    // How It Works Steps
    step1Title: 'Mag-upload ng Larawan',
    step1Desc: 'Kumuha o mag-upload ng malinaw na larawan ng dahon ng pipino',
    step2Title: 'AI Analysis',
    step2Desc: 'Sinusuri ng aming deep learning model ang larawan sa loob ng ilang segundo',
    step3Title: 'Kumuha ng Diagnosis',
    step3Desc: 'Tumanggap ng detalyadong identification ng sakit at severity',
    step4Title: 'Treatment Plan',
    step4Desc: 'Kumuha ng expert recommendations para sa treatment at prevention',

    // Research Modal
    researchAccuracy: 'Accuracy ng Detection',
    researchImages: 'Training Images',
    researchDiseases: 'Mga Sakit na Natukoy',
    researchPoint1: 'Nailathala sa Agricultural AI Journals',
    researchPoint2: 'Kolaborasyon sa Agricultural Universities',
    researchPoint3: 'Patuloy na Pagpapabuti ng Modelo',

    // Demo Modal
    demoVideoPlaceholder: 'Magpe-play ang demo video dito',
    demoOverview: 'Pangkalahatang-ideya ng Demo',
    demoStep1: 'Mag-upload ng larawan ng dahon ng pipino',
    demoStep2: 'AI analysis sa real-time',
    demoStep3: 'Kumuha ng detailed diagnosis report',
    demoStep4: 'Tingnan ang treatment recommendations',

    // Default Modal
    comingSoon: 'Ang content para sa {modal} ay darating pa lamang!',

    // Modal Footer
    getStarted: 'Magsimula',
    close: 'Isara',

    // Footer Tagline
    brandSubtitle: 'Matalinong impormasyon sa kalusugan ng halaman',
    workspace: 'Workspace',
    newScan: 'Bagong pagsusuri',
    scanHistory: 'Kasaysayan ng pagsusuri',
    diseaseGuide: 'Gabay sa sakit',
    community: 'Komunidad',
    needHelp: 'Kailangan ng tulong?',
    visitForum: 'Bisitahin ang forum ng komunidad',
    accountSettings: 'Mga setting ng account',
    preferences: 'Mga kagustuhan',
    signOut: 'Mag-sign out',
    expandSidebar: 'Palawakin ang sidebar',
    collapseSidebar: 'Paliitin ang sidebar',
    displaySettings: 'Mga setting ng display',
    settingsSubtitle: 'Mabilisang kontrol para sa tema, wika, laki ng font, at layout.',
    theme: 'Tema',
    language: 'Wika',
    lightMode: 'Maliwanag na tema',
    darkMode: 'Madilim na tema',
    fontSize: 'Laki ng font',
    normal: 'Karaniwan',
    largeAccessibility: 'Malaki (accessibility)',
    layoutMode: 'Ayos ng layout',
    fullLayout: 'Buong layout',
    compactLayout: 'Compact na layout',
    homeHeroLine1: 'Protektahan ang bawat dahon',
    homeHeroLine2: 'bago kumalat ang sakit.',
    homeTrustNoCard: 'Hindi kailangan ng credit card',
    homeTrustFastResults: 'May resulta sa ilang segundo',
    livePlantScan: 'LIVE NA PAGSUSURI NG HALAMAN',
    moreOptions: 'Iba pang opsyon',
    analysisComplete: 'TAPOS NA ANG PAGSUSURI',
    healthyPlantDetected: 'Natukoy na malusog ang halaman',
    fastResults: 'Mabilis na resulta',
    trustedGrowers: 'Mapagkakatiwalaang kaalaman sa halaman para sa mga magsasaka.',
    builtForDecisions: 'Ginawa para sa mas mabuting pagpapasya',
    homeFeaturesTitle: 'Lahat ng kailangan mo para kumilos',
    homeFeaturesTitleAccent: 'nang maaga at may kumpiyansa.',
    learnMore: 'Alamin pa',
    simpleByDesign: 'Payak at madaling gamitin',
    homeStepsTitle: 'Mula larawan tungo sa',
    homeStepsTitleAccent: 'kapanatagan ng isip.',
    homeStepsDescription: 'Ginagawang malinaw na diagnosis ng Cu-Scan ang larawan ng dahon sa apat na madaling hakbang.',
    seeHowItWorks: 'Tingnan kung paano ito gumagana',
    startToday: 'Magsimula ngayon',
    seconds: 'segundo',
    loginWelcome: 'Maligayang pagbabalik',
    loginHeroTitle: 'Magpalago nang may kumpiyansa,',
    loginHeroAccent: 'isang pagsusuri sa bawat pagkakataon.',
    loginHeroDescription: 'Bumalik sa iyong workspace para sa kalusugan ng halaman, tingnan ang kasaysayan, at gumawa ng matalinong pasya para sa bawat pananim.',
    detectionAccuracyLabel: 'Katumpakan ng pagtukoy',
    averageAnalysis: 'Karaniwang pagsusuri',
    systemReady: 'Handa na ang system',
    aiModelOnline: 'Aktibo ang AI model',
    dashboardReady: 'Handa na ang dashboard para sa iyong mga pananim.',
    signInToCuScan: 'Mag-sign in sa Cu-Scan',
    goodToSeeYou: 'Ikinagagalak naming makita ka muli.',
    continueWorkspace: 'Ilagay ang iyong mga detalye upang magpatuloy sa workspace.',
    emailAddress: 'Email address',
    password: 'Password',
    enterPassword: 'Ilagay ang iyong password',
    hidePassword: 'Itago ang password',
    showPassword: 'Ipakita ang password',
    rememberMe: 'Tandaan ako',
    forgotPassword: 'Nakalimutan ang password?',
    signIn: 'Mag-sign in',
    signingIn: 'Nagla-sign in',
    newToCuScan: 'Bago sa Cu-Scan?',
    createFreeAccount: 'Gumawa ng libreng account',
    verifyYourEmail: 'Beripikahin ang iyong email',
    verificationSent: 'Nagpadala kami ng link ng beripikasyon sa',
    verifyThenReturn: 'Beripikahin ang account at bumalik dito upang mag-sign in.',
    resendVerificationEmail: 'Ipadala muli ang email ng beripikasyon',
    emailRequired: 'Kailangan ang email',
    validEmailRequired: 'Maglagay ng wastong email address',
    passwordRequired: 'Kailangan ang password',
    passwordMinimum: 'Dapat hindi bababa sa 6 na character ang password',
    registerEyebrow: 'Nagsisimula rito ang mas mahusay na pag-aalaga ng pananim',
    registerHeroTitle: 'Alamin ang ipinahihiwatig ng iyong mga halaman.',
    registerHeroDescription: 'Gumawa ng workspace upang matukoy ang sakit ng halaman, masubaybayan ang bawat pagsusuri, at makapagpasya nang may kumpiyansa.',
    fastAiScans: 'Mabilis na pagsusuri gamit ang AI',
    fastAiScansDescription: 'Kumuha ng malinaw na impormasyon mula sa isang larawan.',
    organizedScanHistory: 'Maayos na kasaysayan ng pagsusuri',
    scanHistoryDescription: 'Itago sa iisang lugar ang mga tala ng kalusugan ng pananim.',
    builtForGrowers: 'Ginawa para sa mga magsasaka',
    growerGuidance: 'Kapaki-pakinabang na gabay sa tamang panahon.',
    createAccount: 'Gumawa ng account',
    protectCrops: 'Simulan ang pagprotekta sa iyong mga pananim.',
    setupTime: 'Wala pang isang minuto ang pag-set up.',
    fullName: 'Buong pangalan',
    yourFullName: 'Ilagay ang buong pangalan',
    createPassword: 'Gumawa ng password',
    passwordStrength: 'Lakas ng password',
    useStrongPassword: 'Gumamit ng 8+ character na may malaking titik, maliit na titik, numero, at simbolo.',
    confirmPassword: 'Kumpirmahin ang password',
    repeatPassword: 'Ilagay muli ang password',
    agreeToTerms: 'Sumasang-ayon ako sa',
    and: 'at',
    createAccountButton: 'Gumawa ng account',
    creatingAccount: 'Ginagawa ang account',
    alreadyHaveAccount: 'May account ka na ba?',
    checkYourEmail: 'Tingnan ang iyong email',
    activateAccount: 'Beripikahin ang email upang i-activate ang account.',
    goToSignIn: 'Pumunta sa pag-sign in',
    resendEmail: 'Ipadala muli ang email',
    weak: 'Mahina',
    good: 'Katamtaman',
    strong: 'Malakas',
    none: 'Wala',
    nameRequired: 'Kailangan ang pangalan',
    confirmPasswordRequired: 'Kumpirmahin ang password',
    passwordsDoNotMatch: 'Hindi magkatugma ang mga password',
    acceptTermsRequired: 'Dapat kang sumang-ayon sa mga tuntunin at kundisyon',
    forgotHeroTitle: 'I-reset ang Password',
    forgotHeroDescription: 'Ilagay ang email upang makatanggap ng mga tagubilin sa pag-reset',
    checkYourEmailBang: 'Tingnan ang iyong email!',
    resetInstructionsSent: 'Ipinadala namin ang mga tagubilin sa pag-reset ng password sa',
    sendResetLink: 'Ipadala ang link para mag-reset',
    sending: 'Ipinapadala...',
    backToLogin: 'Bumalik sa pag-login',
    profileSettings: 'Mga setting ng profile',
    manageAccount: 'Pamahalaan ang impormasyon ng iyong account',
    loadingProfile: 'Nilo-load ang profile...',
    retry: 'Subukang muli',
    emailVerified: 'Beripikado ang email',
    emailNotVerified: 'Hindi beripikado ang email',
    memberSince: 'Miyembro mula noong',
    totalAnalyses: 'Kabuuang pagsusuri',
    healthy: 'Malusog',
    infected: 'May sakit',
    recentSevenDays: 'Kamakailan (7 araw)',
    recentAnalyses: 'Mga kamakailang pagsusuri',
    noAnalysesStart: 'Wala pang pagsusuri. Magsimula sa pag-upload ng larawan.',
    noImage: 'Walang larawan',
    confidence: 'Kumpiyansa',
    accountDetails: 'Mga detalye ng account',
    userId: 'ID ng user',
    accountCreated: 'Ginawa ang account',
    lastLogin: 'Huling pag-login',
    emailStatus: 'Katayuan ng email',
    verified: 'Beripikado',
    pendingVerification: 'Naghihintay ng beripikasyon',
    accountActions: 'Mga aksyon sa account',
    uploadNewImage: 'Mag-upload ng bagong larawan',
    viewHistory: 'Tingnan ang kasaysayan',
    resetPassword: 'I-reset ang password',
    logout: 'Mag-logout',
    notAvailable: 'Hindi magagamit',
    unknown: 'Hindi alam',
    noUserLoggedIn: 'Walang naka-login na user',
    failedLoadProfile: 'Hindi ma-load ang impormasyon ng user. Subukang muli.',
    diseaseInfoLabel: 'Impormasyon ng sakit',
    diseaseReference: 'Sanggunian sa sakit',
    cucumberDisease: 'Sakit ng pipino',
    knowledgeBase: 'Gabay-kaalaman',
    diseaseGuideSubtitle: 'Komprehensibong gabay sa pagtukoy, pag-iwas, at paggamot sa mga sakit ng pipino.',
    searchDiseases: 'Maghanap ng mga sakit...',
    categoryAll: 'Lahat',
    categoryFungal: 'Fungal',
    categoryBacterial: 'Bacterial',
    categoryViral: 'Viral',
    categorySoil: 'Sa lupa',
    totalDiseases: 'Kabuuang sakit',
    highRisk: 'Mataas ang panganib',
    fungal: 'Fungal',
    bacterial: 'Bacterial',
    showingDiseases: 'Ipinapakita ang {shown} sa {total} sakit',
    clearFilters: 'Alisin ang mga filter',
    keySymptoms: 'Mahahalagang sintomas',
    aiDetection: 'Pagtukoy ng AI',
    viewDetails: 'Tingnan ang detalye',
    noDiseasesFound: 'Walang nakitang sakit',
    adjustSearchFilters: 'Baguhin ang paghahanap o mga filter',
    resetFilters: 'I-reset ang mga filter',
    needDiagnosis: 'Kailangan ng diagnosis?',
    uploadAffectedPlants: 'Mag-upload ng larawan ng apektadong halaman para suriin gamit ang AI',
    severityHigh: 'Mataas',
    severityMedium: 'Katamtaman',
    soilBorne: 'Nasa lupa',
    historyTitle: 'Kasaysayan ng pagsusuri',
    historySubtitle: 'Subaybayan ang lahat ng pagsusuri at resulta ng dahon ng pipino',
    refresh: 'I-refresh',
    downloadAllPdf: 'I-download lahat bilang PDF',
    healthyPlants: 'Malulusog na halaman',
    infectedDetected: 'Mga natukoy na may sakit',
    loadingHistory: 'Nilo-load ang kasaysayan ng pagsusuri...',
    searchHistory: 'Maghanap ayon sa sakit, petsa, o katayuan...',
    status: 'Katayuan',
    dateRange: 'Saklaw ng petsa',
    sortBy: 'Ayusin ayon sa',
    newestFirst: 'Pinakabago muna',
    oldestFirst: 'Pinakaluma muna',
    highConfidence: 'Mataas na kumpiyansa',
    lowConfidence: 'Mababang kumpiyansa',
    nameAZ: 'Pangalan A-Z',
    nameZA: 'Pangalan Z-A',
    showingAnalyses: 'Ipinapakita ang {shown} sa {total} pagsusuri',
    filtered: 'naka-filter',
    detectedDisease: 'Natukoy na sakit',
    actions: 'Mga aksyon',
    image: 'Larawan',
    filename: 'Pangalan ng file',
    date: 'Petsa',
    noMatchingAnalyses: 'Walang tumutugmang pagsusuri',
    noHistoryYet: 'Wala pang kasaysayan ng pagsusuri',
    adjustHistorySearch: 'Baguhin ang mga filter o termino sa paghahanap',
    uploadFirstImage: 'Mag-upload ng unang larawan ng dahon ng pipino upang magsimula',
    uploadFirst: 'Mag-upload ng unang larawan',
    clearAllFilters: 'Alisin ang lahat ng filter',
    grid: 'Grid',
    table: 'Talahanayan',
    analysisDetails: 'Mga detalye ng pagsusuri',
    fileInformation: 'Impormasyon ng file',
    fileSize: 'Laki ng file',
    uploadDate: 'Petsa ng pag-upload',
    analysisId: 'ID ng pagsusuri',
    analysisResults: 'Mga resulta ng pagsusuri',
    symptomsIdentified: 'Mga natukoy na sintomas',
    recommendations: 'Mga rekomendasyon',
    pdfReport: 'Ulat na PDF',
    downloadPdfReport: 'I-download ang ulat na PDF',
    reportOptionsSingle: 'I-customize ang ulat ng pagsusuri',
    reportOptionsBatch: 'I-customize ang batch report',
    chooseReportContent: 'Piliin kung aling mga seksyon ang isasama sa PDF.',
    reportSections: 'Mga seksyon ng ulat',
    reportIncludeImage: 'Larawan ng halaman',
    reportIncludeFileInfo: 'Impormasyon ng file',
    reportIncludeResults: 'Mga resulta ng pagsusuri',
    reportIncludeSymptoms: 'Mga natukoy na sintomas',
    reportIncludeRecommendations: 'Mga rekomendasyon',
    reportIncludeSummary: 'Buod ng estadistika',
    reportColumns: 'Mga kolum ng resulta',
    reportIncludeFilename: 'Pangalan ng file',
    reportIncludeStatus: 'Katayuan',
    reportIncludeDisease: 'Sakit',
    reportIncludeConfidence: 'Kumpiyansa',
    reportIncludeDate: 'Petsa',
    generatePdf: 'Gumawa ng PDF',
    noReportSectionsSelected: 'Pumili ng kahit isang seksyon o kolum.',
    reportGenerated: 'Handa na ang iyong PDF report.',
    reportTitle: 'Ulat ng pagsusuri sa sakit ng pipino',
    batchReportTitle: 'Batch report ng pagsusuri',
    reportDateGenerated: 'Petsa ng paggawa ng ulat',
    reportSummary: 'Buod ng estadistika',
    totalImages: 'Kabuuang larawan',
    pestReplayNote: 'Inulit ang dating resulta ng peste para sa larawang ito.',
    pestFirstReplayNote: 'Wala pang dating resulta para sa larawang ito. Itinatakda ang pagsusuring ito bilang unang resulta.',
    pestRandomNote: 'Random na demo result; walang konektadong dataset para sa peste.',
    pestSavedToFirestore: 'Na-save sa Firestore ang larawan at resulta ng pagsusuri sa peste.',
    pestSaveFailed: 'Hindi na-save sa Firestore ang pagsusuri sa peste. Tingnan ang koneksyon at mga pahintulot.',
    pestSignInToSave: 'Mag-sign in upang mai-save ang mga larawan ng pagsusuri sa iyong Firestore account.',
    pestImageTooLarge: 'Hindi na-compress nang sapat ang larawang ito para mai-save sa Firestore.',
    reanalyze: 'Suriin muli',
    clearConversation: 'Burahin ang usapan',
    uploadTitle: 'Mag-upload ng larawan ng pipino',
    uploadSubtitle: 'Mag-upload o kumuha ng larawan para suriin kung may sakit',
    scanScopeWarningTitle: 'Mga larawang maaaring suriin',
    scanScopeWarning: 'Suriin lamang ang bunga o dahon ng pipino. Hindi pa hinaharangan ang ibang uri ng larawan, kaya maaaring hindi tumpak ang mga resulta. Plano ang suporta para sa iba pang larawan sa susunod na bersyon.',
    model: 'Modelo',
    loaded: 'Na-load',
    notLoaded: 'Hindi na-load',
    classes: 'Mga klase',
    diseasesCount: '{count} sakit',
    backend: 'Backend',
    running: 'Tumatakbo',
    backendRequired: 'Kailangan ng koneksyon sa backend',
    backendCannotConnect: 'Hindi makakonekta sa backend server',
    startBackend: 'Para simulan ang backend:',
    openTerminal: 'Magbukas ng terminal o command prompt',
    navigateBackend: 'Pumunta sa: C:\\cudics\\backend',
    runBackend: 'Patakbuhin: python app.py',
    offlineLocalNote: 'Maaari pa ring suriin ang mga larawan nang lokal gamit ang sample data.',
    uploadFile: 'Mag-upload ng file',
    useCamera: 'Gamitin ang camera',
    dropImage: 'Ilagay dito ang larawan',
    orBrowse: 'o mag-click upang mag-browse',
    supportsImageFiles: 'Suportado: JPG, PNG, JPEG (Hanggang 10MB)',
    retake: 'Kuhanan muli',
    usePhoto: 'Gamitin ang larawan',
    cameraInstructions: 'Ilagay sa gitna ng frame ang dahon ng pipino para sa pinakamagandang resulta',
    scanDisease: 'Suriin kung may sakit',
    processing: 'Pinoproseso...',
    scanForPest: 'Suriin kung may peste',
    scanning: 'Sinusuri...',
    selectImageHint: 'Pumili ng larawan upang simulan ang pagsusuri',
    backendDisconnectedHint: 'Walang koneksyon sa backend. Sample data lamang ang gagamitin sa pagtukoy ng sakit.',
    uploadToSeeResults: 'Mag-upload ng larawan upang makita ang resulta ng pagsusuri',
    analyzingImage: 'Sinusuri kung may sakit ang larawan...',
    secondsWait: 'Maaaring tumagal ito nang ilang segundo',
    processingErrorTitle: 'Error sa pagproseso',
    trySampleData: 'Subukan sa halip ang sample data',
    pestScanResult: 'Resulta ng pagsusuri sa peste',
    pestGuidance: 'Natukoy na peste at gabay sa paggamot',
    detectedPest: 'Natukoy na peste',
    pest: 'Peste',
    pestScansCount: 'Mga pagsusuri sa peste',
    pestOrDisease: 'Peste / Sakit',
    recommendedCure: 'Inirerekomendang lunas',
    diseaseProbabilities: 'Mga posibilidad ng sakit',
    detectedDisease: 'Natukoy na sakit',
    recommendationsFor: 'Mga rekomendasyon para sa {disease}',
    processed: 'Naproseso',
    sampleDataNote: 'Tandaan: Sample data ang batayan ng resulta. Simulan ang backend para sa aktuwal na pagsusuri.',
    saveReport: 'I-save ang ulat',
    recentUploads: 'Mga kamakailang pagsusuri',
    fileSizeExceeded: 'Lampas sa 10MB ang laki ng file. Pumili ng mas maliit na larawan.',
    cameraAccessError: 'Hindi ma-access ang camera. Tingnan ang mga pahintulot.',
    cameraInsecureContext: 'Kailangan ng ligtas na koneksyon para magamit ang camera. Buksan ang site gamit ang HTTPS (maaari ang localhost para sa lokal na pagsubok).',
    cameraPermissionDenied: 'Tinanggihan ang access sa camera. Payagan ang camera sa mga setting ng browser at i-reload ang pahina.',
    cameraNotFound: 'Walang nakitang camera sa device na ito.',
    cameraUnavailable: 'Hindi magamit ang camera o ginagamit ito ng ibang app.',
    cannotConnectBackend: 'Hindi makakonekta sa backend server. Tiyaking:',
    saveHistoryLogin: 'Gusto mo bang i-save ang kasaysayan ng pagsusuri? Mag-log in.',
    reportSaved: 'Matagumpay na na-save ang ulat!',
    discussionBoard: 'Talakayan',
    growerCommunityTitle: 'Komunidad at sentro ng kaalaman ng mga magsasaka',
    forumDescription: 'Magbahagi ng kaalaman, magtanong, at makipagtulungan sa kapwa magsasaka sa praktikal na forum.',
    recentPosts: 'Mga kamakailang post',
    weeklyEngagement: 'Pakikilahok ngayong linggo',
    newDiscussion: 'Bagong talakayan',
    createPost: 'Gumawa ng post',
    concisePost: 'Panatilihing maikli at kapaki-pakinabang ang post.',
    discussionTitle: 'Pamagat ng talakayan',
    shareWithCommunity: 'Ibahagi sa komunidad ang problema, solusyon, o obserbasyon.',
    addPhoto: 'Magdagdag ng larawan',
    replacePhoto: 'Palitan ang larawan',
    removePhoto: 'Alisin ang larawan',
    selectedPhoto: 'Preview ng napiling larawan',
    invalidPhoto: 'Pumili ng wastong image file.',
    photoTooLarge: 'Dapat 10 MB o mas maliit ang larawan.',
    photoCompressionFailed: 'Hindi naihanda ang larawan para sa Firestore. Subukan ang ibang larawan.',
    posting: 'Ipinapaskil...',
    postDiscussion: 'I-post ang talakayan',
    loadingDiscussions: 'Nilo-load ang mga talakayan...',
    noDiscussions: 'Wala pang talakayan. Magsimula sa isang kapaki-pakinabang na post.',
    communityMember: 'Miyembro ng komunidad',
    postedGrowerForum: 'Ipinaskil sa forum ng mga magsasaka',
    reply: 'Sumagot',
    cancel: 'Kanselahin',
    share: 'Ibahagi',
    hideReplies: 'Itago ang mga sagot',
    showReplies: 'Ipakita ang mga sagot ({count})',
    writeReply: 'Isulat ang iyong sagot...',
    postingReply: 'Ipinapaskil ang sagot...',
    submitReply: 'Ipadala ang sagot',
    communityGuidelines: 'Mga alituntunin ng komunidad',
    respectfulPosts: 'Maging magalang at manatili sa paksa.',
    clearContext: 'Magbahagi ng malinaw na larawan o konteksto.',
    actionableAdvice: 'Magbigay ng nakatutulong at praktikal na payo.',
    popularTopics: 'Mga sikat na paksa',
    plantHealth: 'Kalusugan ng halaman',
    pestControl: 'Pagkontrol sa peste',
    harvestTips: 'Mga payo sa pag-aani',
    justNow: 'Ngayon lang',
    writeOrAddPhoto: 'Magsulat ng mensahe o magdagdag ng larawan.',
    signInToPost: 'Mag-sign in bago mag-post sa forum.',
    postPublished: 'Matagumpay na naipaskil ang post.',
    postFailed: 'Hindi makapag-post ngayon. Subukang muli.',
    enterReply: 'Maglagay ng sagot bago ipadala.',
    signInToReply: 'Mag-sign in bago sumagot.',
    replyPublished: 'Matagumpay na naipaskil ang sagot.',
    replyFailed: 'Hindi maipadala ang sagot. Subukang muli.',
    untitledDiscussion: 'Talakayang walang pamagat',
    welcomeBack: 'Maligayang pagbabalik',
    farmer: 'Magsasaka',
    notifications: 'Mga abiso',
    markAllRead: 'Markahang nabasa lahat',
    noNewNotifications: 'Walang bagong abiso',
    viewAll: 'Tingnan lahat',
    notificationUnread: '{count} hindi pa nababasang abiso',
    notificationUpdates: '{count} hindi pa nababasang update',
    allCaughtUp: 'Wala ka nang hindi pa nababasang abiso',
    restartService: 'I-restart ang serbisyo',
    runDiagnostic: 'Patakbuhin ang diagnosis',
    viewLogs: 'Tingnan ang mga log',
    modelStatusCheck: 'Gumagana ang machine learning model.',
    confirmRestart: 'Sigurado ka bang i-restart ang serbisyo?',
    serviceRestarted: 'Matagumpay na na-restart ang serbisyo.',
    diagnosticRunning: 'Tumatakbo ang pagsusuri ng system.',
    exportStarted: 'Sinimulan ang pag-export ng analytics.',
    analyticsTitle: 'Analytics ng proseso',
    analyticsSubtitle: 'Mga insight sa performance at pagsubaybay ng proseso',
    timeRange: 'Saklaw ng oras',
    totalProcesses: 'Kabuuang proseso',
    fromLastPeriod: 'mula sa nakaraang panahon',
    completed: 'Nakumpleto',
    successRate: 'rate ng tagumpay',
    avgProcessingTime: 'Karaniwang oras ng pagproseso',
    processesUnder5s: '{count} proseso na wala pang 5 segundo',
    activeProcesses: 'Mga aktibong proseso',
    currentlyInProgress: 'Kasalukuyang isinasagawa',
    processVolume: 'Dami ng proseso',
    currentPeriod: 'Kasalukuyang panahon',
    statusDistribution: 'Pamamahagi ng katayuan',
    statuses: 'Mga katayuan',
    performanceMetrics: 'Mga sukatan ng performance',
    processingTime: 'Oras ng pagproseso',
    recentActivity: 'Kamakailang aktibidad',
    noPreviousData: 'Walang nakaraang datos',
    peakVolume: 'Pinakamataas na dami',
    processCountValue: '{count} proseso',
    highestDailyCount: 'Pinakamaraming proseso sa isang araw',
    averageSuccessRate: 'Karaniwang rate ng tagumpay',
    processCompletionPercentage: 'Porsiyento ng nakumpletong proseso',
    responseTime: 'Oras ng pagtugon',
    averageProcessingDuration: 'Karaniwang tagal ng pagproseso',
    activeSessions: 'Mga aktibong session',
    currentlyRunningProcesses: 'Mga prosesong kasalukuyang tumatakbo',
    imageAnalysisProcess: 'Proseso ng pagsusuri ng larawan',
    processingDuration: 'Pinoproseso nang {duration}',
    recentActivityEmpty: 'Walang kamakailang aktibidad',
    startProcessAnalytics: 'Magsimula ng proseso upang makita ang analytics',
    noActivityYet: 'Wala pang aktibidad',
    allActivity: 'Lahat ng aktibidad',
    openAssistant: 'Buksan ang Cu-Scan assistant',
    closeAssistant: 'Isara ang Cu-Scan assistant',
    assistantAriaLabel: 'Assistant para sa mga halaman ng Cu-Scan',
    assistant: 'Cu-Scan Assistant',
    plantSupport: 'Tulong sa kalusugan ng halaman',
    howCanIHelp: 'Paano kita matutulungan sa iyong mga halaman?',
    askSymptoms: 'Magtanong tungkol sa sintomas, pag-iwas sa sakit, o paggamot.',
    analyzingQuestion: 'Sinusuri ang iyong tanong...',
    dismiss: 'Isara',
    askPlantProblem: 'Magtanong tungkol sa problema ng halaman...',
    sendMessage: 'Ipadala ang mensahe',
    chatKeyboardHint: 'Enter para ipadala · Shift + Enter para sa bagong linya',
    chatQuestion1: 'Paano gamutin ang powdery mildew?',
    chatQuestion2: 'Bakit naninilaw at nagkakaroon ng batik ang mga dahon?',
    chatQuestion3: 'Ano ang sanhi ng biglaang pagkalanta?',
    chatQuestion4: 'Paano maiiwasan ang mga sakit na fungal?',
    chatQuestion5: 'Ano ang organikong lunas sa aphids?',
    chatQuestion6: 'Gaano kadalas diligan upang maiwasan ang pagkabulok ng ugat?',
    assistantUnavailable: 'Pansamantalang hindi magagamit ang assistant. Ipinapakita ang pangkalahatang gabay.',
    confirmClearChat: 'Burahin ang usapang ito?',
    pendingStatus: 'Nakahinto',
    failedStatus: 'Nabigo',
    errorStatus: 'Error',
    minutesAgo: '{count} minuto ang nakalipas',
    hoursAgo: '{count} oras ang nakalipas',
    daysAgo: '{count} araw ang nakalipas',
    primaryNavigation: 'Pangunahing nabigasyon',
    dashboardHome: 'Dashboard ng Cu-Scan',
    accessDenied: 'Walang pahintulot',
    loginRequired: 'Kailangan mong mag-login upang makita ang pahinang ito.',
    goToLogin: 'Pumunta sa pag-login',
    unknownSize: 'Hindi alam ang laki',
    invalidDate: 'Hindi wastong petsa',
    invalidTime: 'Hindi wastong oras',
    pdfFailed: 'Hindi nagawa ang ulat na PDF. Subukang muli.',
    batchPdfFailed: 'Hindi nagawa ang batch PDF report.',
    deleteAnalysisConfirm: 'Sigurado ka bang burahin ang pagsusuring ito? Hindi na ito maibabalik.',
    analysisDeleted: 'Matagumpay na nabura ang pagsusuri!',
    deleteFailed: 'Hindi mabura ang pagsusuri. Subukang muli.',
    passwordResetSent: 'Naipadala ang email para i-reset ang password sa {email}',
    verificationEmailSent: 'Naipadala ang email ng beripikasyon. Tingnan ang iyong inbox.',
    operationFailed: 'Hindi nakumpleto ang kahilingan. Subukang muli.',
    recently: 'Kamakailan',
    bytes: 'Bytes',
    today: 'Ngayong araw',
    thisWeek: 'Ngayong linggo',
    thisMonth: 'Ngayong buwan',
    allTime: 'Lahat ng panahon',
    tagline: 'Intelligent na solusyon sa agrikultura para sa mas malulusog na pananim',
  }
}

// Create language store
const languageState = ref({
  current: 'en'
})

export function useLanguage() {
  const applyLanguage = (langCode) => {
    if (!translations[langCode]) return false

    languageState.value.current = langCode
    localStorage.setItem('preferredLanguage', langCode)
    document.documentElement.lang = langCode
    document.documentElement.dir = languages[langCode].dir
    return true
  }

  const setLanguage = async (langCode) => {
    if (!applyLanguage(langCode)) return false

    const user = auth.currentUser
    if (!user) return true

    try {
      await setDoc(doc(db, 'users', user.uid), {
        preferredLanguage: langCode,
        updatedAt: serverTimestamp()
      }, { merge: true })
      return true
    } catch (error) {
      console.error('Failed to save language preference:', error)
      return false
    }
  }

  const loadLanguagePreference = async (user) => {
    if (!user?.uid) return false

    try {
      const userSnapshot = await getDoc(doc(db, 'users', user.uid))
      const savedLanguage = userSnapshot.exists()
        ? userSnapshot.data().preferredLanguage
        : null

      if (applyLanguage(savedLanguage)) return true
    } catch (error) {
      console.error('Failed to load language preference:', error)
    }

    const localLanguage = localStorage.getItem('preferredLanguage')
    return applyLanguage(localLanguage)
  }

  const t = (key, params = {}) => {
    const currentLang = languageState.value.current
    let translation = translations[currentLang]?.[key] || translations.en[key] || key

    // Replace parameters in the translation
    if (params) {
      Object.keys(params).forEach(param => {
        translation = translation.replace(`{${param}}`, params[param])
      })
    }

    return translation
  }

  // Load saved language preference
  const savedLang = localStorage.getItem('preferredLanguage')
  if (savedLang && translations[savedLang]) {
    languageState.value.current = savedLang
  }

  return {
    currentLanguage: computed(() => languageState.value.current),
    languages,
    setLanguage,
    loadLanguagePreference,
    t
  }
}
